### ISSUE TITLE
Package dependency issues when installing from requirements.txt

### ISSUE THREAD

**Issue by alajevar** [Nokia-Bell-Labs/papagei-foundation-model#2]
Hi,
I'm trying to install all the packages from the requirements.txt file. I get this error when I try to do so:

ERROR: Cannot install -r requirements.txt (line 51), -r requirements.txt (line 67) and attrs==22.1.0 because these package versions have conflicting dependencies.The conflict is caused by:    The user requested attrs==22.1.0    glom 22.1.0 depends on attrs    jsonschema 4.22.0 depends on attrs>=22.2.0To fix this you could try to:1. loosen the range of package versions you've specified2. remove package versions to allow pip to attempt to solve the dependency conflict

**Comment by arvind1609** [comment]
Hi, 
Fixed the requirements.txt and added installation instructions for easier feature extraction.
